---
galaxy_info:
  role_name: infinispan_cache
  namespace: middleware_automation
  author: Guido Grazioli
  description: Configure Infinispan or DataGrid cache at runtime.
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: "2.9"

  platforms:
   - name: EL
     versions:
     - 8

  galaxy_tags:
    - infinispan
    - datagrid
    - redhat
    - rhel
    - rhn
    - server
    - linux
