---
infinispan_bind_address: localhost     # noqa var-naming
infinispan_port: 11222                 # noqa var-naming
infinispan_tls: False                  # noqa var-naming
infinispan_deployer_user: supervisor   # noqa var-naming
infinispan_cache_xml: ''
infinispan_cache_config: {}
